person_templates_small = [
    "A photo of a {}",
    "A rendering of a {}",
    "A cropped photo of a {}",
    "A portrait of a {}",
    "A close-up shot of a {}",
    "A full-body image of a {}",
    "An artistic sketch of a {}",
    "A black-and-white photograph of a {}",
    "A candid shot of a {}",
    # "A digital illustration of a {}",
    # "A stylized caricature of a {}",
    "A profile view of a {}",
    # "A group shot featuring a {}",
    "A dynamic action pose of a {}",
    "A studio portrait of a {}",
    "An abstract representation of a {}",
    "A casual snapshot of a {} outdoors.",
    "A futuristic hologram of a {}",
    # "A detailed 3D model of a {}",
]

imagenet_templates_small = [
    "a photo of a {}",
    "a rendering of a {}",
    "a cropped photo of the {}",
    "the photo of a {}",
    "a photo of a clean {}",
    "a photo of a dirty {}",
    "a dark photo of the {}",
    "a photo of my {}",
    "a photo of the cool {}",
    "a close-up photo of a {}",
    "a bright photo of the {}",
    "a cropped photo of a {}",
    "a photo of the {}",
    "a good photo of the {}",
    "a photo of one {}",
    "a close-up photo of the {}",
    "a rendition of the {}",
    "a photo of the clean {}",
    "a rendition of a {}",
    "a photo of a nice {}",
    "a good photo of a {}",
    "a photo of the nice {}",
    "a photo of the small {}",
    "a photo of the weird {}",
    "a photo of the large {}",
    "a photo of a cool {}",
    "a photo of a small {}",
]

imagenet_style_templates_small = [
    "a painting in the style of {}",
    "a rendering in the style of {}",
    "a cropped painting in the style of {}",
    "the painting in the style of {}",
    "a clean painting in the style of {}",
    "a dirty painting in the style of {}",
    "a dark painting in the style of {}",
    "a picture in the style of {}",
    "a cool painting in the style of {}",
    "a close-up painting in the style of {}",
    "a bright painting in the style of {}",
    "a cropped painting in the style of {}",
    "a good painting in the style of {}",
    "a close-up painting in the style of {}",
    "a rendition in the style of {}",
    "a nice painting in the style of {}",
    "a small painting in the style of {}",
    "a weird painting in the style of {}",
    "a large painting in the style of {}",
]
